// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwXjGuKUdu97Xu8tr0hw6I2d0vlOuKRA',
    appId: '1:723710159644:web:afb8f29df5a9950778a8d9',
    messagingSenderId: '723710159644',
    projectId: 'sutapp93',
    authDomain: 'sutapp93.firebaseapp.com',
    storageBucket: 'sutapp93.firebasestorage.app',
    measurementId: 'G-M27Q8S3PQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsWBh4iN2d-UZW83j7dILMbuT-uYS9UFw',
    appId: '1:723710159644:android:e8bf1a4cfea4bc0178a8d9',
    messagingSenderId: '723710159644',
    projectId: 'sutapp93',
    storageBucket: 'sutapp93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNYNu5yusnptnKJG9yc6ANyT2faq2xHk',
    appId: '1:723710159644:ios:805530949dcdb4ef78a8d9',
    messagingSenderId: '723710159644',
    projectId: 'sutapp93',
    storageBucket: 'sutapp93.firebasestorage.app',
    iosBundleId: 'com.sutapp.sutapp',
  );

}