// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0-FtYShX4AInMnieL5PHVxmAujWvEhGs',
    appId: '1:216356501452:web:a0f72b9c489b63b5dd4f69',
    messagingSenderId: '216356501452',
    projectId: 'sutapp-9d33c',
    authDomain: 'sutapp-9d33c.firebaseapp.com',
    storageBucket: 'sutapp-9d33c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSu9hE1TB5TkHUrltsLXZOssPCtN3zEGg',
    appId: '1:216356501452:android:5052e4dc9a563d7fdd4f69',
    messagingSenderId: '216356501452',
    projectId: 'sutapp-9d33c',
    storageBucket: 'sutapp-9d33c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-IavSLbSnvL5EUubIqI5LlZe46miJTw',
    appId: '1:216356501452:ios:48fea2d578584fe7dd4f69',
    messagingSenderId: '216356501452',
    projectId: 'sutapp-9d33c',
    storageBucket: 'sutapp-9d33c.firebasestorage.app',
    iosBundleId: 'com.sutapp.sutapp',
  );

}